### ISSUE TITLE
Compliance with systemd

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/piratebox_ynh#1]
The first release of the Internet Cube should use Debian Jessie. Because we use a sysvinit service, we need to convert it to the systemd format and replace all the "service" commands by "systemctl". Status commands must be replaced by the is-active option.

**Comment by jvaubourg** [comment]
Should be okay from 71ecc2c28400f9341b814a618e5cf91b6d6d8955 (branch "jessie").

We need strong tests before merging (and losing wheezy compatibility).

**Comment by sbadia** [comment]
Fixed by #6
